package:
 name: sentani_mpkg
 version: 0.1.2

requirements:
 build:
  - python
 run:
  - python
  - bokeh ==0.9.0
  - seaborn ==0.6.0
  - ipython-notebook ==3.2.0
  - scipy ==0.15.1
  - matplotlib ==1.4.3
  - pysentani ==0.2.1